name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write private key to a file
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > /tmp/ec2_key.pem
        chmod 600 /tmp/ec2_key.pem

    - name: Verify and Print Secrets
      run: |
        echo "EC2_HOST is ${{ secrets.EC2_HOST }}"
        echo "EC2_USER is ${{ secrets.EC2_USER }}"


    - name: Upload code to EC2 instance
      run: |
        scp -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no -r ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/flask-aws-Ec2/


    - name: SSH into EC2 and restart services
      run: |
        ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/flask-aws-Ec2
          source myenv/bin/activate
          git pull origin main
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
