name: Test Secrets

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Print EC2_HOST
      run: |
        echo "EC2_HOST is ${{ secrets.EC2_HOST }}"
